### ISSUE TITLE
Sustain pedal causes notes to stick after releasing

### ISSUE THREAD

**Issue by cfaia** [matkatmusic/ChordieApp_IssueTracker#29] opened 2020-06-16 06:27 UTC
Operating System version Mac OSX 10.15
    Steps to reproduce the issue. USe sustain pedal, play some chords, hold the chords and release the pedal, play more chords, some notes are not cleared and stay selected while new notes are added
    expected behavior: notes should be cleared when pedal released
    behavior actually experienced. notes not cleared
    crash log if you happen to have one. no crash

**Comment by cfaia** [comment] 2020-06-16 06:54
This also happens when playing notes on the computer keyboard and MIDI keyboard simultaneously. Notes will get stuck and won't clear. Would be nice to have a clear button (panic) so that we don't have to reset to clear it...

**Comment by matkatmusic** [comment] 2020-06-16 07:39
```
Steps to reproduce the issue. 
USe sustain pedal, 
play some chords, 
hold the chords and release the pedal, 
play more chords, 
some notes are not cleared and stay selected while new notes are added
```
Can you record a midi file that causes this and attach it or email it?   I can't replicate this.  Also, the computer keyboard is disabled as an input source for the Piano keyboard at the bottom of the app window.   so I'm not sure how you're using the computer keyboard to trigger anything.

If you haven't, please grab the latest build from https://gumroad.com/library and let me know if the bug is still there.

**Comment by cfaia** [comment] 2020-06-16 08:02
I’ve done a quick screen recording of the different problems. These problem are random, but persistent.

https://www.dropbox.com/s/ppwyx3f80l1lqly/Screen%20Recording%202020-06-16%20at%2009.55.17.mov?dl=0

C

**Comment by matkatmusic** [comment] 2020-06-16 16:44
If you have a different problem, create a separate issue.

**Comment by matkatmusic** [comment] 2020-06-16 16:46
Would you mind resetting the database and resetting all settings to default via the menus?

**Comment by matkatmusic** [comment] 2020-06-16 23:20
hey @cfaia please let me know if resetting the database solved the issue.  it's under the Fretboard menu.

**Comment by cfaia** [comment] 2020-06-17 06:39
Yes, this fixes the problem, but there is still the odd stuck note when playing many notes at once very quickly.

**Comment by matkatmusic** [comment] 2020-06-17 07:08
Alright, if you can email me a midi file of what you played that triggered this, this will help me to debug and fix this.

**Comment by matkatmusic** [comment] 2020-06-18 01:31
hey @cfaia can you email a midi file to me of what you played to trigger this bug?

**Comment by matkatmusic** [comment] 2020-06-19 23:07
@cfaia please send me a midi file that triggers this bug!

**Comment by cfaia** [comment] 2020-06-20 14:50
Here you go… Sorry, really busy at the moment...

C

**Comment by matkatmusic** [comment] 2020-06-20 17:23
@cfaia nothing is attached here.  Please send it via email!

**Comment by lcalder** [comment] 2020-06-24 06:22
It happens when I play complex music with pedal. It will eventually clear but sometimes can take up to a minute. I think it is trying to look up those increasingly complex chords and each note added will add to the time it takes to do a lookup. To reproduce, just play a chromatic scale with the pedal down. After three octaves, for example, you will have to wait 10 to 15 seconds after you have released the pedal for it to clear.

**Comment by matkatmusic** [comment] 2020-06-24 06:32
Duplicate of https://github.com/matkatmusic/ChordieApp_IssueTracker/issues/46

**Closed as completed by matkatmusic** 2020-06-24 06:32 UTC
Labels: duplicate
