### ISSUE TITLE
Issue when entering open strings on fretboard

### ISSUE THREAD

**Issue by gittoaster** [matkatmusic/ChordieApp_IssueTracker#59] opened 2020-06-29 15:56 UTC
Win10
Issue actual
enter all open strings and the expected overlay is missing
expected
to see the gui overlay on all open strings selected

video
https://1drv.ms/v/s!AlWU8e7V8SIuhNsPvyJkVs79n3WLpg?e=gNhGq6

**Comment by matkatmusic** [comment] 2020-06-29 19:10
thanks for reporting!

**Comment by matkatmusic** [comment] 2020-06-29 23:47
holy crap!! what a wild goose chase to track this one down.  took a good 4 hours and came down to commenting out the stuff that's commented out below:
```
if( /*str.isPlucked() && str.isFretted() &&*/ str.getPitch() != -1 )
```

Fixed in next build.

**Closed as completed by matkatmusic** 2020-06-29 23:47 UTC
Labels: bug, Resolved

**Comment by gittoaster** [comment] 2020-06-30 01:35
wow, good work!
I had a question about another topic.  Do you intend to use the mouse to select notes on the keyboard?  I'm not sure if that is in this version or not.

**Comment by ghost** [comment] 2020-06-30 07:18
I just did what was fixed but now the BOTTOM + / - only shows up to 9 strings but the top +/- will give you 12 strings. Also the selected 9 strings disappear after adding 10 strings.

https://www.dropbox.com/s/aqtjwvzmssz09dv/Screen%20Recording%202020-06-30%20at%2003.10.51.mov?dl=0

**Comment by matkatmusic** [comment] 2020-06-30 07:55
> wow, good work!
> I had a question about another topic. Do you intend to use the mouse to select notes on the keyboard? I'm not sure if that is in this version or not.

It's planned for later.

**Comment by matkatmusic** [comment] 2020-06-30 07:58
> I just did what was fixed but now the BOTTOM + / - only shows up to 9 strings but the top +/- will give you 12 strings. Also the selected 9 strings disappear after adding 10 strings.
> 
> https://www.dropbox.com/s/aqtjwvzmssz09dv/Screen%20Recording%202020-06-30%20at%2003.10.51.mov?dl=0

@pimtja 
The tuners are constrained to the range of the piano notes.  When you clicked that D on the lowest string, it lit up the lowest D on the piano. 

I think you might have discovered a small bug that no one else would ever encounter unless they went hunting for it like you did lol.  Please create a separate issue for that.

**Comment by matkatmusic** [comment] 2020-07-01 06:04
> I just did what was fixed but now the BOTTOM + / - only shows up to 9 strings but the top +/- will give you 12 strings. Also the selected 9 strings disappear after adding 10 strings.
> 
> https://www.dropbox.com/s/aqtjwvzmssz09dv/Screen%20Recording%202020-06-30%20at%2003.10.51.mov?dl=0

Hey, @pimtja  this turned out to be that the fretboard engine is still processing in the background when you add the 10th string.  that's why you don't see anything.  You changed the tuning, so it is trying to figure out a playable fretboard for the notes that were entered.  So, it's not a bug.  It just isn't showing you that it is thinking.  I have added some visual feedback to indicate that it is processing.

**Comment by ghost** [comment] 2020-07-01 06:29
> > wow, good work!
> > I had a question about another topic. Do you intend to use the mouse to select notes on the keyboard? I'm not sure if that is in this version or not.
> 
> It's planned for later.

I wouldn't mind being able to use the mouse especially if there is no access to a midi keyboard. I haven't even hooked up my keyboard yet because I want to see what I can do solely from the laptop itself…

**Comment by ghost** [comment] 2020-07-01 06:30
> > I just did what was fixed but now the BOTTOM + / - only shows up to 9 strings but the top +/- will give you 12 strings. Also the selected 9 strings disappear after adding 10 strings.
> > https://www.dropbox.com/s/aqtjwvzmssz09dv/Screen%20Recording%202020-06-30%20at%2003.10.51.mov?dl=0
> 
> Hey, @pimtja this turned out to be that the fretboard engine is still processing in the background when you add the 10th string. that's why you don't see anything. You changed the tuning, so it is trying to figure out a playable fretboard for the notes that were entered. So, it's not a bug. It just isn't showing you that it is thinking. I have added some visual feedback to indicate that it is processing.

Alrighty works for me…
