### ISSUE TITLE
Chordie sometimes claims no internet connection falsely

### ISSUE THREAD

**Issue by lcalder** [matkatmusic/ChordieApp_IssueTracker#49] opened 2020-06-23 15:12 UTC
I use chordie with separate windows captured in OBS studio. sometimes chordie "disappears" and when I check on it, it has returned to single window mode and with the line, "Chordie requires an internet connection..."
I have gigabit internet running continuously with actual upload/download speeds in the 870-950mbs+ range at all times as reported by my google mesh network and speedtest.net.
This problems sometimes happens as frequently as twice a day, or somedays not at all...

**Comment by matkatmusic** [comment] 2020-06-23 19:38
I'm pretty sure this is server-related, not app related.  I'll look into it.  Also, you're lucky for having those speeds.  I'm jealous!

**Comment by lcalder** [comment] 2020-06-24 06:27
Today I was teaching and suddenly my chordie windows disappeared from my outgoing feed. I use the "separate windows" option and then video capture within obs studio to grab the piano keys, as well as the chordie manuscript window and chord window. When I checked, it had gone back to single window as was requesting that I submit my registration details. After a resubmitted them, it didn't require me to restart as it normally does when this happens to me. I clicked on "separate windows" but nothing happened until it clicked a couple of times. Then it seemed to work normally again.

**Comment by matkatmusic** [comment] 2020-06-24 06:34
You're describing 2 separate issues.  Please make a new issue for this one you're describing here.
```
When I checked, it had gone back to single window as was requesting that I submit my registration details.
After a resubmitted them, it didn't require me to restart as it normally does when this happens to me.
I clicked on "separate windows" but nothing happened until it clicked a couple of times. Then it seemed to work normally again.
```

**Comment by Morgen82** [comment] 2020-06-28 04:56
OS: Win 7-64 Pro
Confirm random 'no internet connection'.
In my case, always followed by new authentication. (see issue 51 for this component)
Does no internet connection mean unable to connect to authentication server?

**Comment by matkatmusic** [comment] 2020-06-28 05:26
`Does no internet connection mean unable to connect to the authentication server?`
Yes.  Make sure you're on the latest build.  I have not been able to re-create this experience on my end, even if I run the app for an hour.

**Comment by Morgen82** [comment] 2020-06-29 04:15
I apologize.  I haven't been clear.  It has only happened on the first launch of a new build followed by the new athentication sequence. (51)  It usually requires 2 restarts to get to the app.  I just launched this build again and it started up without incident on the first try.  I'm assuming now that this is all working as intended for each new beta build. (That is that there are no authenticated users in the database for each new build, it throws this error 'no internet connection' ,restarts, proceeds to offer the beta authentication license sequence  again, restarts one more time into the app.) In any case, it all appears to be functioning correctly now.

**Comment by matkatmusic** [comment] 2020-06-29 08:35
Thanks @Morgen82 

You shouldn't be seeing 'no internet connection', though.   And I did reset the database of authenticated users once after releasing one of the builds, but for the most recent builds, I had changed what the app uses to determine the computer's ID.  Any requests to re-auth are due to those changes.

**Comment by matkatmusic** [comment] 2020-06-29 20:00
I pushed out a new build last night. Are you still experiencing this @Morgen82 
If you are not, please report that it is resolved so I can close this issue.

**Comment by Morgen82** [comment] 2020-06-29 20:17
no error on this build!

**Comment by vadillo89** [comment] 2020-07-09 23:10
Hi, same problem over here. I just bought chordie and I've been unable to use it because it falsely claims I don't have an internet connection. Help please.

**Comment by lcalder** [comment] 2020-07-09 23:21
I've waited for the new release to be issued before continuing to report on this because it seemed that a lot of things were gradually being worked out over the beta phase and I didn't want to keep bothering the developer.
Now, I have been using the release version (not beta) and in a day with 10 hours teaching, the chordie program is a constant pain as it just seems to want me to constantly reauthorize it (two times in a 10-hour period) and claims there is not internet (7 to 10 times) in a 10-hour period. I am using zoom this entire period of time to give lessons and THAT is internet-based and works.

I'm am wondering how chordie can be less requiring of constant attention, which mostly requires quitting and restarting, because the "try again" button doesn't seem to work when I press it...

Since I am not using advanced esoteric jazz chords and primarily use chordie to show the keys I am pressing above the videocam of my actual keyboard and hands it is doubly frustrating for it to have to constantly be tethered to the outside internet connection for such simple behavior. Perhaps having a little green "light" appear on the chord window if it detects "internet connections" whereby advance lookup is possible from the online database, or else show a red "light" on the status of the window and just show basic internally-calculated chord labeling so the software is not so "noisy" and constantly requiring attention.
Each time I restart I have to wait the several seconds for it to call home.... It is really frustrating.
I would be happy to pay $100 for just a version that doesn't keep pestering me and doesn't require constant internet connection...

**Comment by matkatmusic** [comment] 2020-07-16 21:58
I will investigate this.

**Comment by Morgen82** [comment] 2020-07-17 05:54
OS: Win 7-64 Pro
I hesitate to say anything but...  Sometimes, usually after a new patch, Chordie will stall at the 'calling home' point and reports no internet connection.  I reported it fixed on the previous release, but it did it again on this release.  However, restarting the OS fixes it.  This tells me that while Chordie might be more susceptible to connections issues, there might also be other factors contributing to the problem.  My suggestion to users is to launch Chordie first and limit where possible other background apps that require an internet connection and see if things don't improve.  It's just a suggestion.  I'm really out of my depth when it comes to networking, sockets, server connections to cache on email accounts, etc. 
My antivirus, Avast, also finds Chordie to be highly suspicious and runs a deep check on each new iteration.
That said, there is probably something that could be improved in the networking component of Chordie as well.
Hope this info helps.

**Closed as completed** 2020-08-03 22:36 UTC
Labels: Needs investigating
