### ISSUE TITLE
Windows in Separate windows mode cannot be minialized or closed

### ISSUE THREAD

**Issue by chordig** [matkatmusic/ChordieApp_IssueTracker#54] opened 2020-06-24 14:56 UTC
In the current beta version on Windows, windows in Separate windows mode cannot be minimized or closed. Only the ChordieApp window has this capability - however, it only minimizes this one window. Especially the minimization option is always useful for every window.

**Comment by matkatmusic** [comment] 2020-06-24 22:46
Duplicate of https://github.com/matkatmusic/ChordieApp_IssueTracker/issues/43

**Closed as completed by matkatmusic** 2020-06-24 22:46 UTC
Labels: duplicate
