### ISSUE TITLE
Windows disappear

### ISSUE THREAD

**Issue by JorgeGaPa** [matkatmusic/ChordieApp_IssueTracker#50] opened 2020-06-23 16:39 UTC
Being working with separate windows, after a few minutes that I was in Sibelius, wanting to go back to Chordie, the windows didn't appear anymore, it just showed this:
![ChordieWindow](https://user-images.githubusercontent.com/67218601/85430613-970c0000-b53d-11ea-9675-6fdf71913ad1.jpg)
![ChordieWindow2](https://user-images.githubusercontent.com/67218601/85430616-97a49680-b53d-11ea-99b6-f0346a37d278.jpg)

**Comment by matkatmusic** [comment] 2020-06-23 19:40
I fixed something last night that seems related to this, but haven't pushed the update out to the testers.  I will tonight though.  When it comes out, let me know if the issue is resolved.

**Comment by JorgeGaPa** [comment] 2020-06-23 20:13
Ok. Thanks!

**Comment by chordig** [comment] 2020-06-24 14:46
It happens to me too. Window looks the same.
(version from the link from the email sent approx 7 hours ago)

**Comment by matkatmusic** [comment] 2020-06-24 22:41
@chordig please provide steps to reproduce.   I can't reproduce this on my end.  Reminder: Any version of Windows prior to Windows 10 is unsupported.

**Comment by JorgeGaPa** [comment] 2020-06-26 04:27
My operating system is Windows 10-64 bits

1. I opened the Sibelius
2. I opened the Chordie and separated the windows
3. I was working on Sibelius for 10 minutes (while this was happening, Chordie's windows were in the background).
4. When I wanted to go back to Chordie to check some chords, the windows were gone. There was only the one in the image I sent earlier. I had to restart Chordie.
That's it.
Thank you

**Comment by matkatmusic** [comment] 2020-06-26 10:14
Does this happen with any other program when Chordie is in the background or just with Sibelius?

**Comment by JorgeGaPa** [comment] 2020-06-26 21:21
I have not used Chordie together with another application and it gives me the same error. Only once was I using Cubase Al 10.5 and Chordie at the same time, and repeatedly I got the Chordie window asking me to reconnect and enter my serial number, but the serial number was already written in this window on all occasions.

**Comment by matkatmusic** [comment] 2020-06-26 22:59
Your sentence is confusing.
> I have **_not_** used Chordie together with another application
> and it gives me the same error.

Which one is it?  
You have NOT used chordie with another application?   
Or you HAVE used it with another application and you experienced the same error?

**Comment by JorgeGaPa** [comment] 2020-06-27 00:08
Sorry I don't speak English and I'm trusting the Google translator.
The error of when windows disappear has only happened to me with Sibelius.
But when Chordie repeatedly asked me to reconnect and asked for my serial number, it was when I was working with Cubase.

**Comment by matkatmusic** [comment] 2020-06-29 19:56
I pushed out a new build last night.  Are you still experiencing this bug @JorgeGaPa @chordig 
If you are **not**, please report that it is resolved so I can close this issue.

**Comment by JorgeGaPa** [comment] 2020-06-30 07:21
I have been testing the update all day today and have not had any problems.

**Closed as completed** 2020-06-30 07:28 UTC
Labels: Resolved
